export const CREATE_MEDICINE = "CREATE_MEDICINE";
export const GET_MEDICINE = "GET_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const SELECT_MEDICINE = "SELECT_MEDICINE";
export const CLEAR_MEDICINE = "CLEAR_MEDICINE";
export const DELETE_SELECTED_MEDICINE = "DELETE_SELECTED_MEDICINE";
